---
modelname: VGG16_test1
batch_size: 4
image_height: 650
image_width: 650

data:
    - train_path: ../../../data/allTrain.csv
    - validate_path: ../../../data/allVal.csv
    - image_dir: ../../data/
    - log_file: csvLog.csv
    - checkpoint_path: checkpoints/

model:
    - learning_rate: 0.01
