---
modelname: resnet50_freeze_stdMPL_dropout25
batch_size: 32
image_height: 224
image_width: 224

data:
    - train_path: ../../data_resize/allTrain.csv
    - validate_path: ../../data_resize/allTest.csv
    - image_dir: ../../data_resize/
    - log_file: csvLog.csv
    - checkpoint_path: checkpoints/

model:
    - learning_rate: 0.001
